services:
  api:
    build: .
    container_name: polarify_api
    ports:
      - "54321:54321"
    volumes:
      - .:/code
    command: fastapi dev app/main.py --port 54321 --host 0.0.0.0
    environment:
      - DATABASE_URL=postgresql://postgres_user:1234@db:5432/postgres_polarify
      - TEST_DATABASE_URL=postgresql://test_user:test@test_db:5432/test_postgres_polarify
    depends_on:
      - db
      - test_db

  db:
    image: postgres:13
    container_name: polarify_db
    environment:
      POSTGRES_DB: postgres_polarify
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  test_db:
    image: postgres:13
    container_name: polarify_test_db
    environment:
      POSTGRES_DB: test_postgres_polarify
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test
    ports:
      - "5444:5432"

  # Development purpose
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  postgres_data:
    driver: local